export enum SocketEvent {
  SERVER_CONNECT = "connection",
  SERVER_DISCONNECT = "disconnect",
  CLIENT_CONNECT = "connect",
  CLIENT_DISCONNECT = "disconnect",
  JOIN_SERVER = "JOIN_SERVER",
  LEAVE_SERVER = "LEAVE_SERVER",
  SEND_MESSAGE = "SEND_MESSAGE",
  ON_MESSAGE_SENT = "ON_MESSAGE_SENT",
}
